##########
# Collab #
##########
collab_staging:
  # Auto deploy on master.
  auto_deploy_on: refs/heads/master
  # Wait for our ci pipeline to pass.
  required_contexts: ["ci_collab"]
  environment: alpha
  payload:
    image: bluescape/collab
    tag: ${{ short_sha }}

####################
# Worker Framework #
####################
worker_staging:
  # Auto deploy on master.
  auto_deploy_on: refs/heads/master
  # Wait for our ci pipeline to pass.
  required_contexts: ["ci_worker"]
  environment: beta
  payload:
    image: bluescape/worker
    tag: ${{ short_sha }}